export const FETCH_COIN_LIST = 'FETCH_COIN_LIST';
export const FETCH_COIN = 'FETCH_COIN';
export const FETCH_COIN_DETAILS = 'FETCH_COIN_DETAILS';
export const FETCH_COIN_PRICE_HISTORY = 'FETCH_COIN_PRICE_HISTORY';
export const FETCH_COIN_ORDER_BOOK = 'FETCH_COIN_ORDER_BOOK';
export const FETCH_COIN_TRANSACTION = 'FETCH_COIN_TRANSACTION';